# MCP 服务器配置
server:
  host: localhost
  port: 8080

# GitHub 配置
github:
  repo: csdn
  branch: main

# 工具配置
tools:
  - name: code-generator
    enabled: true
  - name: code-analyzer
    enabled: true 